name: Push to Docker Hub

on:
  push:
    tags:
      - '*'

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Docker tag
        env:
          DOCKER_TAG: ${{ github.ref }}
        run: |
          DOCKER_TAG=${DOCKER_TAG#refs/tags/}
          DOCKER_TAG=${DOCKER_TAG/\//-}
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $DOCKER_HUB_USERNAME/django-markdown-editor:$DOCKER_TAG .

      - name: Log in to Docker Hub
        run: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_TOKEN
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: docker push $DOCKER_HUB_USERNAME/django-markdown-editor:$DOCKER_TAG
